---
- hosts: '{{ host }}'
  gather_facts: no
  tasks:
    - name: copy tarball to host
      copy:
        src: ./tarballs/{{tar}}
        dest: /root/{{tar}}

    - name: load container from tarball
      docker_image:
        name: "{{tar}}"
        load_path: /root/{{tar}}
        state: present
        source: load