---
- hosts: '{{ host }}'
  become: true

  tasks:
    # Creates the number of containers defined by the variable create_containers, using values from vars file
    - name: Create default containers
      docker_container:
        name: "{{ container_name }}{{ item }}"
        image: "{{ image }}"
        command: "{{ container_command }}"
        state: present
      with_sequence: count={{ create_containers }}
