---
- name: setup vpn clients
  hosts: clients
  become: yes
  tasks:
  - name: install wireguard package
    apt:
      name: wireguard
      state: latest
      update_cache: yes

  - name: generate private key
    shell:
      cmd: umask 077 && wg genkey | tee privatekey | wg pubkey > publickey
      chdir: /etc/wireguard
      creates: /etc/wireguard/publickey

  - name: get public key
    command: cat /etc/wireguard/publickey
    register: publickey_contents
    changed_when: False

  # Save results as a fact, so we can use it when templating wg0.conf for the
  # server
  - name: set public key fact
    set_fact:
      pubkey: "{{ publickey_contents.stdout }}"

  - name: create client wireguard config
    template:
      dest: /etc/wireguard/wg0.conf
      src: client_wg0.conf.j2
      owner: root
      group: root
      mode: '0600'

- name: setup vpn server
  hosts: localhost
  vars:
      privkey: eA5PRhadFVZfxKOFuEFH0gE8eRGLaePnkxGg+/WKG2A=
      pubkey: pWYtnC0O4N2YAqDXGBs1ECb8QFMs6oTBl9uzYRxOlnA=
  tasks:
  - name: install wireguard package
    apt:
      name: wireguard
      state: latest
      update_cache: yes

  - name: create server wireguard config
    template:
      dest: /etc/wireguard/wg0.conf
      src: server_wg0.conf.j2
      owner: root
      group: root
      mode: '0600'
    notify: reload wireguard config

  - name: enable and persist ip forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: "1"
      state: present
      sysctl_set: yes
      reload: yes

  - name: start wireguard and enable on boot
    systemd:
      name: wg-quick@wg0
      enabled: yes
      state: started

  handlers:
  # Reloads config without disrupting current peer sessions, but does not
  # re-run PostUp commands. Notify this handler on server config changes.
  - name: reload wireguard config
    shell: wg syncconf wg0 <(wg-quick strip wg0)
    args:
      executable: /bin/bash


- name: start vpn on clients
  hosts: clients
  become: yes
  tasks:
   - name: restart wireguard
     shell: wg-quick down wg0; wg-quick up wg0
     args:
      executable: /bin/bash

